title: Scammer Buffer
markdown: kramdown
url: "carefaze.com"
baseurl: "/"
description: "A blog about scams, frauds, how to avoid them. And the tactics used by scammers to trick you."
# for atom feed
author:
  name: Scammer Buffer
  email: legal.asset.07@gmail.com

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections

collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

